### ISSUE TITLE
issues while running poly benchmarks

### ISSUE THREAD

**Issue by sangeeta0201** [uwplse/herbgrind#37]
Hello,

I have been trying poly benchmarks with herbgrind. As you have mentioned that output should be printed by the benchmarks to get floating point errors. I tried cholesky kernel and it does print the output but unfortunately, herbgrind does not report any error.

```
./herbgrind.sh polybench-c-3.2/cholesky 
==2937== Herbgrind, a valgrind tool for Herbie
==2937== Copyright (C) 2016-2017, and GNU GPL'd, by Alex Sanchez-Stern
==2937== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==2937== Command: polybench-c-3.2/cholesky
==2937== 
starting kernel
going to print
==2937== 
Didn't find any marks!
``` 

I am using polybench-c-3.2.

**Comment by sangeeta0201** [comment]
Hello,

Can you please update on this issue. It would be a great help.

**Comment by pavpanchekha** [comment]
Are you confident there is floating-point error in this benchmark? IIRC, only a few Polybench benchmarks did; I think Gram-Schmidt Orthonormalization (but you'd have to check the paper). If there's no floating-point error, Herbgrind won't print anything.

**Comment by HazardousPeach** [comment]
Hey @sangeeta0201,
I can't reproduce this issue right now. Did you make any modifications to your polybench? When I run the `cholesky` benchmark in polybench-c-3.2, it doesn't print the "starting kernel" and "going to print" messages, and when it finishes, it produces an output file with one mark.

I ran on the latest version of Herbgrind on `master`, which was recently updated to a newer version of Valgrind (the older version doesn't run on modern `ld` on my machine anymore, hence the upgrade), maybe that fixed the issue? Can you confirm whether the issue is still present on your end, and if so, do you have any more details to reproduce?

**Comment by sangeeta0201** [comment]
Hi Alex and Pavan,

I have tried with the latest version from git and now I am getting error reports. Thank you so much.
