### ISSUE TITLE
Execution issue

### ISSUE THREAD

**Issue by hbrunie** [uwplse/herbgrind#49]
Running Herbgrind on a scientific application (python, C++, using boost), I obtained an assertion error:
instrument/floattypes.c:1285
Cannot meet types Vt_Double and Vt_NonFloat

I don't know why it was thrown, and how could I correct it in my code.
Thank you,

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/5767146/64999649-77082b80-d89d-11e9-8127-19c611444078.png">

**Comment by hbrunie** [comment]
Here is the stack as shown by valgrind(herbgrind tool) when it fails on the assertion:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/5767146/64999847-23e2a880-d89e-11e9-8df8-86b40464c23f.png">

**Comment by HazardousPeach** [comment]
That error is due to Herbgrind finding an unsafe type conversion when trying to infer the types of values in the assembly code. In this case, judging by your backtrace, it's because of the libm implementation of exp2l, which does integer-like bit manipulation in order to implement the exp2 function. Normally, these kinds of libm tricks aren't a problem, because the calls into libm are intercepted and dealt with seperately, so there's no need to instrument that assembly. Unfortunately, we forgot to add exp2l to our list of functions to wrap, so you hit this issue. This omission is fixed in a98afab.

**Comment by hbrunie** [comment]
Thank you for the complete and precise answer.
