### ISSUE TITLE
Too specific explicit path to mkdir

### ISSUE THREAD

**Issue by drfortran** [uwplse/herbgrind#61]
Hi,
sorry for elementary buglets: the explicit path to mkdir does not point to the one on my OS
…
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/home/lafage/herbgrind/valgrind/herbgrind-install/include/valgrind'
/bin/bash: line 3: /usr/bin/mkdir: No such file or directory
Makefile:483: recipe for target 'install-nobase_pkgincludeHEADERS' failed
…
where it is expected in /bin/mkdir instead of /usr/bin/mkdir.

I would consider either the simple relative addressing 'mkdir' or, if it is not too specific to GNU Makefile the $(MKDIR) variable.

Regards,
Vincent

**Comment by HazardousPeach** [comment]
Hey Vincent,

Unfortunately, this bug is also outside of the Herbgrind source proper, in this case it appears to be an issue with the Valgrind makefile (that target doesn't exist in the Herbgrind one). If a newer version of Valgrind fixes the issue, you can change the VALGRIND_REVISION variable in the Herbgrind makefile to the hash of the newer commit, and it will attempt to build with that version (no guarantees though, as I've only tested on the currently pinned version). Otherwise, I think a symlinks is your best bet.

I would be interested to hear what you're using Herbgrind for, it's always nice to know the users!
Alex

**Comment by drfortran** [comment]
Understood. Thanks !

Well, as for me, I used to be a physicist, deep in computational High Energy Physics, just before the era of C++, and encountering a catalog of weird floating point computations, I learnt the hard way to respect epsilons. When I turned into an IT engineer, I had to clean much legacy code, and tried as much as possible to use tools to get some idea of what happened there.
Now, I am looking for ways to speed nuclear experiments online code, in particular by reducing to float (small direct speedup but less cache miss expected) provided it keeps enough accuracy.
So I put much hope in Herbgrind and Verrou to check the sensitive parts of the code.

**Comment by HazardousPeach** [comment]
Wow, that's cool! You might also want to check out [Herbie](herbie.uwplse.org), which helps you write accurate code by taking the formula you want to compute, and generating floating point code which does it well. That way, when you find a problem, you don't necessarily have to revert back to wide precision.
